"""remove some columns add talkingspoints to db

Revision ID: 2e58ec2d8f03
Revises: 878e2c918c5b
Create Date: 2024-01-05 23:10:31.037273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e58ec2d8f03'
down_revision: Union[str, None] = '878e2c918c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talking_point',
    sa.Column('friend_id', sa.UUID(), nullable=False),
    sa.Column('point', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.drop_column('gift_idea', 'price')
    op.drop_column('gift_idea', 'url')
    op.drop_column('gift_idea', 'description')
    op.drop_column('gift_idea', 'done_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_idea', sa.Column('done_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('gift_idea', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gift_idea', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gift_idea', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_table('talking_point', schema='public')
    # ### end Alembic commands ###
