"""add contact table

Revision ID: 76b0ad78f56a
Revises: 570f3e1c9876
Create Date: 2023-12-24 23:17:22.045066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b0ad78f56a'
down_revision: Union[str, None] = '570f3e1c9876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('friend_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('via_telephone', sa.Boolean(), nullable=False),
    sa.Column('via_email', sa.Boolean(), nullable=False),
    sa.Column('via_messenger', sa.Boolean(), nullable=False),
    sa.Column('in_person', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
