"""modify gift_idea logic

Revision ID: dde958d254b1
Revises: 77e33f8d8e27
Create Date: 2024-02-09 21:53:53.447891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde958d254b1'
down_revision: Union[str, None] = '77e33f8d8e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_idea', sa.Column('used_on', sa.Date(), nullable=True))
    op.add_column('gift_idea', sa.Column('obtained', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('gift_idea', 'done')
    op.add_column('important_event', sa.Column('requires_gift', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('important_event', 'requires_gift')
    op.add_column('gift_idea', sa.Column('done', sa.BOOLEAN(), server_default='false', nullable=False))
    op.drop_column('gift_idea', 'obtained')
    op.drop_column('gift_idea', 'used_on')
    # ### end Alembic commands ###
